openapi: "3.0.0"
info:
  version: 1.0.0
  title: Artipie - OpenAPI 3.0
  description:
    This is Atripie Server based on the OpenAPI 3.0 specification.
  license:
    name: MIT
externalDocs:
  description: Find out more about Artipie
  url: https://github.com/artipie
tags:
  - name: repository
    description: Operations about repository
paths:
  /api/v1/repository/list:
    get:
      summary: List all repositories.
      operationId: listAll
      tags:
        - repository
      responses:
        '200':
          description: A list of the existing repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/repository/{rname}:
    get:
      summary: Get repository settings
      operationId: getRepo
      tags:
        - repository
      parameters:
        - name: rname
          in: path
          required: true
          description: Name of the repository
          schema:
            type: string
      responses:
        '200':
          description: Full repository settings
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AliasRepository'
                  - $ref: '#/components/schemas/FullRepository'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Create repository
      operationId: createRepo
      tags:
        - repository
      parameters:
        - name: rname
          in: path
          required: true
          description: Name of the repository
          schema:
            type: string
      requestBody:
        description: Create a new repository
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Repository'
        required: true
      responses:
        '200':
          description: Creates a new repository with name {rname}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullRepository'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Remove repository
      operationId: removeRepo
      tags:
        - repository
      parameters:
        - name: rname
          in: path
          required: true
          description: Name of the repository
          schema:
            type: string
      responses:
        '200':
          description: Remove a repository with name {rname}
        '400':
          description: Wrong repository name
        '404':
          description: Repository not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/repository/{rname}/storages:
    get:
      summary: Get repository storage aliases
      operationId: getRepoAliases
      tags:
        - storage aliases
      parameters:
        - name: rname
          in: path
          required: true
          description: Name of the repository
          schema:
            type: string
      responses:
        '200':
          description: Full storage alias settings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorageAlias'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/repository/{rname}/storages/{aname}:
    put:
      summary: Add or update repository storage alias
      operationId: addRepoAlias
      tags:
        - storage aliases
      parameters:
        - name: rname
          in: path
          required: true
          description: Name of the repository
          schema:
            type: string
        - name: aname
          in: path
          required: true
          description: Name of the storage alias
          schema:
            type: string
      requestBody:
        description: Create a new storage alias
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Storage'
        required: true
      responses:
        '201':
          description: Alias added successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete repository storage alias
      operationId: deleteRepoAlias
      tags:
        - storage aliases
      parameters:
        - name: rname
          in: path
          required: true
          description: Name of the repository
          schema:
            type: string
        - name: aname
          in: path
          required: true
          description: Name of the storage alias
          schema:
            type: string
      responses:
        '200':
          description: Alias was removed successfully
        '404':
          description: Alias does not exist
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/storages:
    get:
      summary: Get common Artipie storage aliases
      operationId: getAliases
      tags:
        - storage aliases
      responses:
        '200':
          description: Full aliases settings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorageAlias'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/storages/{aname}:
    put:
      summary: Add or update common Artipie storage alias
      operationId: addAlias
      tags:
        - storage aliases
      parameters:
        - name: aname
          in: path
          required: true
          description: Name of the storage alias
          schema:
            type: string
      requestBody:
        description: Create a new storage alias
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Storage'
        required: true
      responses:
        '201':
          description: Alias added successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete common Artipie storage alias
      operationId: deleteAlias
      tags:
        - storage aliases
      parameters:
        - name: aname
          in: path
          required: true
          description: Name of the storage alias
          schema:
            type: string
      responses:
        '200':
          description: Alias was removed successfully
        '404':
          description: Alias does not exis
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Repository:
      type: object
      required:
        - repo
      properties:
        repo:
          type: object
    FullRepository:
      type: object
      required:
        - type
        - storage
      properties:
        type:
          type: string
        storage:
          type: object
    AliasRepository:
      type: object
      required:
        - type
        - storage
      properties:
        type:
          type: string
        storage:
          type: string
    StorageAlias:
      type: object
      required:
        - alias
        - storage
      properties:
        alias:
          type: string
        storage:
          type: object
    Storage:
      type: object
      required:
        - type
      properties:
        type:
          type: string
