openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
paths:
  /api/v1/repository/list:
    get:
      summary: List all repositories.
      operationId: listAll
      tags:
        - repository
      responses:
        '200':
          description: A list of the existing repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/repository/list/{uname}:
    get:
      summary: List repositories of the user.
      operationId: list
      tags:
        - repository
      parameters:
        - name: uname
          in: path
          required: true
          description: User name
          schema:
            type: string
      responses:
        '200':
          description: A list of the existing repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/repository/{uname}/{rname}:
    get:
      summary: Get repository seettings
      operationId: getRepo
      tags:
        - repository
      parameters:
        - name: uname
          in: path
          required: true
          description: User name
          schema:
            type: string
        - name: rname
          in: path
          required: true
          description: Name of the repository
          schema:
            type: string
      responses:
        '200':
          description: Full repository settings
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AliasRepository'
                  - $ref: '#/components/schemas/FullRepository'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    FullRepository:
      type: object
      required:
        - type
        - storage
      properties:
        type:
          type: string
        storage:
          type: object
    AliasRepository:
      type: object
      required:
        - type
        - storage
      properties:
        type:
          type: string
        storage:
          type: string
