openapi: "3.0.0"
info:
  version: 1.0.0
  title: Artipie - OpenAPI 3.0
  description:
    This is Atripie Server based on the OpenAPI 3.0 specification.
  license:
    name: MIT
externalDocs:
  description: Find out more about Artipie
  url: https://github.com/artipie
tags:
  - name: settings
    description: Operations about settings
paths:
  /api/v1/settings/port:
    get:
      summary: Artipie server-side port (repositories default port).
      operationId: port
      tags:
        - settings
      responses:
        '200':
          description: Artipie server-side port (repositories default port)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Port'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/settings/layout:
    get:
      summary: Repository layout.
      operationId: layout
      tags:
        - settings
      responses:
        '200':
          description: Layout of repository
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Layout'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Port:
      type: object
      required:
        - port
      properties:
        port:
          type: integer
    Layout:
      type: object
      required:
        - layout
      properties:
        layout:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string