FROM python:3.7
ENV REV=0
ENV DEBIAN_FRONTEND noninteractive
ENV no_proxy host.docker.internal,host.testcontainers.internal,localhost,127.0.0.1
RUN apt update -y -o APT::Update::Error-Mode=any && apt dist-upgrade -y
RUN apt install --no-install-recommends -y curl xz-utils netcat-traditional
RUN pip3 install -U pip setuptools
RUN pip3 install -U twine
COPY pypi-repo/ /w/

COPY prepMinio.sh minio-bin-20231120.txz /w/
RUN /w/prepMinio.sh

WORKDIR "/w"

RUN rm -rf /w/minio-bin-20231120.txz
RUN apt -y autoremove -y --purge && apt clean -y && rm -rf /var/cache/apt/archives /var/lib/apt/lists
RUN du -hs /w/*
