name: Release Docker images
on:
  push:
    tags:
      - "v*"
jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-21-maven-
          runs-on: ubuntu-latest
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}
      - run: mvn install -DskipTests
      - run: mvn -B deploy -Pubuntu-docker -DskipTests
        working-directory: artipie-main
      - run: mvn versions:set -DnewVersion=latest
      - run: mvn install -DskipTests
      - run: mvn -B deploy -Pubuntu-docker -DskipTests
        working-directory: artipie-main
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
