name: Create Maven release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set version
        run: mvn -B versions:set -DnewVersion=${{ env.TAG }} versions:commit
      - name: Create settings.xml
        uses: whelk-io/maven-settings-xml-action@v15
        with:
          servers: |
            [
              {
                "id": "oss.sonatype.org",
                "username": "${{ secrets.SONATYPE_USER }}",
                "password": "${{ secrets.SONATYPE_PASSWORD }}"
              }
            ]
          profiles: |
            [
              {
                "id": "artipie",
                "properties": {
                  "gpg.keyname": "${{ secrets.GPG_KEYNAME }}",
                  "gpg.passphrase": "${{ secrets.GPG_PASSPHRASE }}"
                }
              }
            ]
      - run: mvn -B install -DskipTests
      - run: mvn deploy -pl '!:artipie-main,!:helm-bench,!:debian-bench,!:conda-bench,!:rpm-bench' -Psonatype,gpg-sign -DskipTests --errors
        env:
          MAVEN_OPTS: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
