---
name: Reports
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Run tests
        run: mvn -B verify -Pjacoco
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
