---
name: Reports
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Linux JDK
        run: |
          curl --silent -o ${{ runner.temp }}/jdk-17_linux-x64_bin.tar.gz \
            https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
      - name: Set up Linux JDK
        uses: actions/setup-java@v2
        with:
          distribution: jdkfile
          jdkFile: ${{ runner.temp }}/jdk-17_linux-x64_bin.tar.gz
          java-version: 17
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Run tests
        run: mvn -B verify -Pjacoco
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
